name       : readline
version    : 6.3.008
release    : 6
source     :
    - https://ftp.gnu.org/gnu/readline/readline-6.3.tar.gz : 56ba6071b9462f980c5a72ab0023893b65ba6debb4eeb475d7a563dc65cafd43
homepage   : https://tiswww.case.edu/php/chet/readline/rltop.html
license    : GPL-3.0-or-later
component  : system.base
summary    : Another cute console display library
description: |
    The GNU Readline library provides a set of functions for use by applications that allow users to edit command lines as they are typed in. Both Emacs and vi editing modes are available. The Readline library includes additional functions to maintain a list of previously-entered command lines, to recall and perhaps reedit those lines, and perform csh-like history expansion on previous commands.
builddeps  :
    - pkgconfig32(ncursesw)
patterns   :
    - devel:
        - /usr/share/info
        - /usr/share/man/man3
emul32     : yes
setup      : |
    %apply_patches
    %configure --disable-static \
        --with-curses
build      : |
    %make SHLIB_LIBS=-lncurses
install    : |
    %make_install

    # it's empty
    rmdir $installdir/usr/bin

    rm -fr $installdir/usr/share/doc/readline
